name: CI Pipeline

on:
  push:
    branches: [development*]
  pull_request:
    branches: [development*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run WIFI Test
        run: pio test -e win_test_wifi -f "test_win_wifi"  
        
      - name: Run pc_comm Test
        run: pio test -e win_test_pc_comm -f "test_win_pc_comm"  

      - name: run Light Test
        run: pio test -e win_test_light -f "test_win_light"

      - name: Run Connection Controller Test
        run: pio test -e win_test_connection_controller -f "test_connection_controller"

      - name: Run Monitoring Controller Test
        run: pio test -e win_test_monitoring_controller -f "test_monitoring_controller" 

      - name: Run Security Controller Test
        run: pio test -e win_test_security_controller -f "test_security_controller""      