name: CI Pipeline

on:
  push:
    branches: [development*]
  pull_request:
    branches: [development*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run WIFI Test.
        run: pio test -e win_test_wifi -f "test_win_wifi"  
        
      - name: Run pc_comm Test.
        run: pio test -e win_test_pc_comm -f "test_win_pc_comm"  

      - name: Run Light Test.
        run: pio test -e win_test_light -f "test_win_light"

      - name: Run Connection Control Test.
        run: pio test -e win_test_control_module -f "test_connection_control"

      - name: Run Monitoring Control Test.
        run: pio test -e win_test_control_module -f "test_monitoring_control" 

      - name: Run Security Control Test.
        run: pio test -e win_test_control_module -f "test_security_control"

      - name: Run Display Control Test.
        run: pio test -e win_test_control_module -f "test_display_control"

      - name: Run Buttons Control Test.
        run: pio test -e win_test_control_module -f "test_buttons_control"   

      - name: Run Application Test.
        run: pio test -e win_test_application -f "test_application"        

      - name: Build The Project.
        run: pio run -e ATmega2560